// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Exercise struct {
	ID          string  `json:"_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type NewExercise struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}
